CREATE DATABASE census_data_db;

USE census_data_db;

DROP TABLE IF EXISTS us_population;
CREATE TABLE us_population (
    `universe` VARCHAR(1) NOT NULL,
    `month` INTEGER,
    `year` INTEGER,
    `age` INTEGER,
    `tot_pop` INTEGER,
    `tot_male` INTEGER,
    `tot_female` INTEGER,
    `wa_male` INTEGER,
    `wa_female` INTEGER,
    `ba_male` INTEGER,
    `ba_female` INTEGER,
    `ia_male` INTEGER,
    `ia_female` INTEGER,
    `aa_male` INTEGER,
    `aa_female` INTEGER,
    `na_male` INTEGER,
    `na_female` INTEGER,
    `tom_male` INTEGER,
    `tom_female` INTEGER,
    `wac_male` INTEGER,
    `wac_female` INTEGER,
    `bac_male` INTEGER,
    `bac_female` INTEGER,
    `iac_male` INTEGER,
    `iac_female` INTEGER,
    `aac_male` INTEGER,
    `aac_female` INTEGER,
    `nac_male` INTEGER,
    `nac_female` INTEGER,
    `nh_male` INTEGER,
    `nh_female` INTEGER,
    `nhwa_male` INTEGER,
    `nhwa_female` INTEGER,
    `nhba_male` INTEGER,
    `nhba_female` INTEGER,
    `nhia_male` INTEGER,
    `nhia_female` INTEGER,
    `nhaa_male` INTEGER,
    `nhaa_female` INTEGER,
    `nhna_male` INTEGER,
    `nhna_female` INTEGER,
    `nhtom_male` INTEGER,
    `nhtom_female` INTEGER,
    `nhwac_male` INTEGER,
    `nhwac_female` INTEGER,
    `nhbac_male` INTEGER,
    `nhbac_female` INTEGER,
    `nhiac_male` INTEGER,
    `nhiac_female` INTEGER,
    `nhaac_male` INTEGER,
    `nhaac_female` INTEGER,
    `nhnac_male` INTEGER,
    `nhnac_female` INTEGER,
    `h_male` INTEGER,
    `h_female` INTEGER,
    `hwa_male` INTEGER,
    `hwa_female` INTEGER,
    `hba_male` INTEGER,
    `hba_female` INTEGER,
    `hia_male` INTEGER,
    `hia_female` INTEGER,
    `haa_male` INTEGER,
    `haa_female` INTEGER,
    `hna_male` INTEGER,
    `hna_female` INTEGER,
    `htom_male` INTEGER,
    `htom_female` INTEGER,
    `hwac_male` INTEGER,
    `hwac_female` INTEGER,
    `hbac_male` INTEGER,
    `hbac_female` INTEGER,
    `hiac_male` INTEGER,
    `hiac_female` INTEGER,
    `haac_male` INTEGER,
    `haac_female` INTEGER,
    `hnac_male` INTEGER,
    `hnac_female` INTEGER,
    `id` INTEGER AUTO_INCREMENT NOT NULL,
    PRIMARY KEY(id)
    );
    
LOAD DATA LOCAL INFILE 'D:\\UDAB_Projects\\Racial_Health_Disparities\\Census_Data\\Census_Raw_Data_20092016.csv' 
INTO TABLE us_population 
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SELECT * FROM us_population;